GET http://localhost:3000

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000
Content-Type: application/json

{
    "name": "John"
}
###
PUT http://localhost:3000
Content-Type: application/json

{
    "name": "John"
}

###
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "password": "Doe23;:42"
}

###
DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTcwMDIyNzc4NywiZXhwIjoxNzA4MDAzNzg3fQ.u0UDUEoCIHysGlf_KlKM4DfA8xtHBNfzo4Non9eF6Ss
